/**:
  controller_manager:
    ros__parameters:
      use_sim_time: False
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      joint_trajectory_command_broadcaster:
        type: joint_trajectory_command_broadcaster/JointTrajectoryCommandBroadcaster

/**:
  joint_trajectory_command_broadcaster:
    ros__parameters:
      joints:
      - left_thumb_1_joint
      - left_thumb_2_joint
      - left_index_1_joint
      - left_middle_1_joint
      - left_ring_1_joint
      - left_little_1_joint

      interfaces:
        - position

      offsets:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
