services:
  ffw:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ffw_container
    tty: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - /dev:/dev
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    privileged: true
    command: bash
