# ffw_basic is shared by BG2, BH5, and F1.

# Changing the camera type causes an error because the camera URDF is fixed.
# If you want to change it, modularize the camera URDF first.
bg2:
  body: ffw_body
  base: ffw_basic
  end_tool: rh_p12_rn_a
  head_camera_type: zed
sg2:
  body: ffw_body
  base: ffw_swerve
  end_tool: rh_p12_rn_a
  head_camera_type: zed
bh5:
  body: ffw_body
  base: ffw_basic
  end_tool: hx5_d20_rev2
  head_camera_type: zed
sh5:
  body: ffw_body
  base: ffw_swerve
  end_tool: hx5_d20_rev2
  head_camera_type: zed
f1:
  body: ffw_body_f
  base: ffw_basic
  end_tool: hx2_d1
  head_camera_type: realsense
f2:
  body: ffw_body_f
  base: ffw_swerve_f
  end_tool: hx2_d1
  head_camera_type: realsense
