services:
  ai_worker:
    container_name: ai_worker
    image: robotis/ai-worker:2.0.0
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /var/log/ai_worker_navigation
        chown nobody:nogroup /var/log/ai_worker_navigation
        chmod 02755 /var/log/ai_worker_navigation
        exec /init
    tty: true
    restart: always
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    ipc: host
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /usr/local/zed/settings/:/usr/local/zed/settings/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ./workspace:/workspace
      - ../:/root/ros2_ws/src/ai_worker/
      - /var/run/robotis/agent_sockets/ai_worker:/var/run/agent
      - /home/robotis/cyclo_manager:/opt/cyclo_manager:ro
      - ./s6-services/common:/usr/local/lib/s6-services:ro
      - ./s6-services/ai_worker_navigation:/etc/s6-overlay/s6-rc.d/ai_worker_navigation:ro
      - ./s6-services/ai_worker_navigation-log:/etc/s6-overlay/s6-rc.d/ai_worker_navigation-log:ro
      - ./s6-services/ai_worker_map_save:/etc/s6-overlay/s6-rc.d/ai_worker_map_save:ro
      - /home/robotis/blank/ai_worker/docker/s6-services/ai_worker_bringup/run:/etc/s6-overlay/s6-rc.d/ai_worker_bringup/run:ro
    privileged: true
