/**:
  # controller_spawn is a custom launch configuration.
  # controller_spawn is not an actual ROS 2 node.
  # Read by the follower launch to spawn controllers and run initialization; add controllers here for automatic startup.
  controller_spawn:
    ros__parameters:
      controllers:
        - arm_l_controller
        - arm_r_controller
        - head_controller
        - lift_controller
        - joint_state_broadcaster
        - ffw_robot_manager
      executors:
        - arm_l_joint_trajectory_executor
        - arm_r_joint_trajectory_executor
        - head_joint_trajectory_executor
        - lift_joint_trajectory_executor

  controller_manager:
    ros__parameters:
      update_rate: 100
      arm_l_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      arm_r_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      head_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      lift_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      ffw_robot_manager:
        type: ffw_robot_manager/FfwRobotManager

  arm_l_controller:
    ros__parameters:
      joints: [arm_l_joint1, arm_l_joint2, arm_l_joint3, arm_l_joint4,
               arm_l_joint5, arm_l_joint6, arm_l_joint7]
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true

  arm_r_controller:
    ros__parameters:
      joints: [arm_r_joint1, arm_r_joint2, arm_r_joint3, arm_r_joint4,
               arm_r_joint5, arm_r_joint6, arm_r_joint7]
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true

  head_controller:
    ros__parameters:
      joints: [head_joint1, head_joint2]
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true

  lift_controller:
    ros__parameters:
      joints: [lift_joint]
      command_interfaces: [position]
      state_interfaces: [position, velocity]
      allow_nonzero_velocity_at_trajectory_end: true

  ffw_robot_manager:
    ros__parameters:
      disable_torque_on_error: false
      set_led_error_on_error: true
