arm_l_joint_trajectory_executor:
  ros__parameters:
    joint_names:
      - arm_l_joint1
      - arm_l_joint2
      - arm_l_joint3
      - arm_l_joint4
      - arm_l_joint5
      - arm_l_joint6
      - arm_l_joint7
      - gripper_l_joint1
    step_names: [table_ready]
    table_ready:
      - 1.1383335868601994
      - 0.16853415484402948
      - 0.08995359213960642
      - -1.6951566286377817
      - 0.27226960562479596
      - -0.9465500356997781
      - -0.11196998211609252
      - 0.0
    duration: 6.0
    position_tolerance: 0.1
    velocity_tolerance: 0.01
    action_topic: '/arm_l_controller/follow_joint_trajectory'
    trajectory_topic: '/leader/joint_trajectory_command_broadcaster_left/joint_trajectory'
    joint_states_topic: '/joint_states'

arm_r_joint_trajectory_executor:
  ros__parameters:
    joint_names:
      - arm_r_joint1
      - arm_r_joint2
      - arm_r_joint3
      - arm_r_joint4
      - arm_r_joint5
      - arm_r_joint6
      - arm_r_joint7
      - gripper_r_joint1
    step_names: [table_ready]
    table_ready:
      - 1.1433190244208276
      - -0.13817811315876127
      - -0.04756538864936023
      - -1.7302943760602871
      - -0.11737349872306227
      - -0.925337957617297
      - 0.19234304058867288
      - 0.0015339807878856412
    duration: 6.0
    position_tolerance: 0.1
    velocity_tolerance: 0.01
    action_topic: '/arm_r_controller/follow_joint_trajectory'
    trajectory_topic: '/leader/joint_trajectory_command_broadcaster_right/joint_trajectory'
    joint_states_topic: '/joint_states'

head_joint_trajectory_executor:
  ros__parameters:
    joint_names:
      - head_joint1
      - head_joint2
    step_names: [table_view]
    table_view: [0.6918253353362172, 0.009203884727106981]
    duration: 4.0
    position_tolerance: 0.1
    velocity_tolerance: 0.01
    action_topic: '/head_controller/follow_joint_trajectory'
    trajectory_topic: '/leader/joystick_controller_left/joint_trajectory'
    joint_states_topic: '/joint_states'

lift_joint_trajectory_executor:
  ros__parameters:
    joint_names:
      - lift_joint
    step_names: [table_ready]
    table_ready: [-0.1]
    duration: 6.0
    position_tolerance: 0.1
    velocity_tolerance: 0.01
    action_topic: '/lift_controller/follow_joint_trajectory'
    trajectory_topic: '/leader/joystick_controller_right/joint_trajectory'
    joint_states_topic: '/joint_states'
