metadata:
  robot: ffw_bg2_rev4_follower
  captured_at: ''        # ISO 8601, set by capture node
  generator: ''          # script + version, set by capture node

offsets:  # bit values
  # RIGHT ARM
  dxl1: 34809                # arm_r_joint1
  dxl2: 476                # arm_r_joint2
  dxl3: 32919                # arm_r_joint3
  dxl4: 124                # arm_r_joint4
  dxl5: 0                # arm_r_joint5
  dxl6: -321                # arm_r_joint6
  dxl7: 207                # arm_r_joint7

  # LEFT ARM
  dxl31: 31029               # arm_l_joint1
  dxl32: -170              # arm_l_joint2
  dxl33: 33620               # arm_l_joint3
  dxl34: 581               # arm_l_joint4
  dxl35: 0               # arm_l_joint5
  dxl36: -38               # arm_l_joint6
  dxl37: -256               # arm_l_joint7

  #32768