# RealSense camera serials per machine.
# Key must match: hostname -s  (see camera_realsense.launch.py)

# Used when hostname is not listed under hosts (optional fallback)
default:
  camera1_serial: "'335122270624'"
  camera2_serial: "'335122272052'"

# To find your hostname, enter "hostname" in the CLI. And add it to the list below.
hosts:
  ffw-SNPR48A1022:
    camera1_serial: "'230422272973'"
    camera2_serial: "'230322270437'"

  ffw-SNPR48A1050:
    camera1_serial: "'335122270624'"
    camera2_serial: "'335122272052'"

  ffw-SNPR48A1085:
    camera1_serial: "'335122270562'"
    camera2_serial: "'335122272198'"

  ffw-SNPR48A1107:
    camera1_serial: "'335122273183'"
    camera2_serial: "'315122271771'"

  ffw-SNPR48A1109:
    camera1_serial: "'335122271364'"
    camera2_serial: "'335122273200'"

  ffw-SNPR48A1110:
    camera1_serial: "'335122272376'"
    camera2_serial: "'335122271144'"




# # intel
# # Serial numbers for RealSense cameras
# # Prefix with underscore (_) to force string type in ROS 2 parameter system
# camera1_serial: _128422270387
# camera2_serial: _128422270627
# camera3_serial: _049522250475