metadata:
  robot: ffw_bg2_rev4_follower
  captured_at: ''        # ISO 8601, set by capture node
  generator: ''          # script + version, set by capture node

offsets:  # bit values
  # RIGHT ARM
  dxl1: 29328                # arm_r_joint1
  dxl2: 547                # arm_r_joint2
  dxl3: 37156                # arm_r_joint3
  dxl4: 269                # arm_r_joint4
  dxl5: -553                # arm_r_joint5
  dxl6: -151                # arm_r_joint6
  dxl7: 953                # arm_r_joint7

  # LEFT ARM
  dxl31: 30870               # arm_l_joint1
  dxl32: 406              # arm_l_joint2
  dxl33: 28524               # arm_l_joint3
  dxl34: -412               # arm_l_joint4
  dxl35: -186               # arm_l_joint5
  dxl36: -13735               # arm_l_joint6
  dxl37: -293               # arm_l_joint7

  #32768, -151875